name: Build

on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os: ['ubuntu-18.04', 'macOS-10.15', 'windows-2019']
        go: ['1.14.x']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: github/super-linter@v3
      env:
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_GO: true
      if: startsWith(matrix.os, 'ubuntu-')
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - run: make lint test
